---
- name: Get OS Release Info
  shell: cat /etc/*-release
- name: Change SELinux Policy
  shell: echo 0 >/selinux/enforce
- name: Install python-selinux
  yum: name=libselinux-python state=latest
- name: Update system
  yum: name=* state=latest
- name: Update Python Setup Tools
  yum: name=python-setuptools state=latest
- name: Install Development Tools # yum groupinstall 'Development Tools'
  yum: name="@Development Tools" state=latest
- name: Install Common Development packages
  shell: yum -y install man ruby wget curl git-core gcc g++ make automake autoconf curl-devel openssl-devel zlib-devel apr-devel apr-util-devel sqlite-deve ruby-rdoc ruby-devel rubygems libselinux-python php-pear php-devel nc python-dev ncurses-devel glibc-static
- name: Update gems
  shell: gem update --system
- name: Install Bundler gem
  shell: gem install bundler
- name: Install Pip
  shell: easy_install pip 
- name: Install virtualenv
  shell: pip install virtualenv


