---
- name: Install httpd
  yum: name=httpd-2.2.15 state=present

- name: Install SSL
  shell: yum -y install mod_ssl openssl

- name: Install Hello World PHP script
  template:
    src={{ httpd_index }}
    dest=/var/www/html/index.php 
    mode=0664

- name: Copy .htaccess
  template:
    src={{ httpd_htaccess }}
    dest=/var/www/html/.htaccess
    mode=644
  when: httpd_htaccess is defined

- name: Create /data dir
  file: state=directory path=/data/

- name: Copy .htpasswd
  template:
    src={{ httpd_htpasswd }}
    dest=/data/.htpasswd
    mode=644
  when: httpd_htpasswd is defined

- name: Disable firewall
  service: name=iptables state=stopped enabled=no

- name: Backup httpd.conf
  shell: yes n | cp -i /etc/httpd/conf/httpd.conf /etc/httpd/conf/httpd.conf.`date +%Y%m%d-%H%M%S`
  when: httpd_conf is defined

- name: Copy httpd.conf
  copy: src={{ httpd_conf }} dest=/etc/httpd/conf/httpd.conf
  when: httpd_conf is defined

- name: Backup ssl.conf
  shell: yes n | cp -i /etc/httpd/conf.d/ssl.conf /etc/httpd/conf.d/ssl.conf.`date +%Y%m%d-%H%M%S`
  when: ssl_conf is defined

- name: Copy ssl.conf
  copy: src={{ ssl_conf }} dest=/etc/httpd/conf.d/ssl.conf
  when: ssl_conf is defined

- name: Restart httpd
  service: name=httpd state=restarted enabled=yes
