- name: Install packages
  shell: yum -y install php-pgsql python-psycopg2 postgresql-server postgresql postgresql-devel

- name: Initiate database
  command: service postgresql initdb
  ignore_errors: True

- name: Start PostgreSQL and enable at boot
  service: name=postgresql
          enabled=yes
          state=started

- name: Change password
  command: su - postgres -c "psql -U postgres -d postgres -c \"alter user postgres with password '{{ postgres_password }}';\""
  notify: restart postgresql
